// MongoDB seed script - Sample rail industry articles for IRISO Bau AG
// This runs automatically when the mongo container starts for the first time

db = db.getSiblingDB('practicedb');

db.articles.insertMany([
  {
    baseUrl: "https://www.sbb.ch",
    url: "https://www.sbb.ch/de/bahnhof-services/am-bahnhof/bahnhoefe/news-luzern-2025",
    title: "SBB startet Modernisierung des Bahnhofs Luzern",
    dateText: "10.01.2026",
    date: new Date("2026-01-10"),
    teaser: "Umfassende Erneuerung der Infrastruktur am Bahnhof Luzern geplant.",
    generatedTeaser: "Die SBB hat die langerwartete Modernisierung des Bahnhofs Luzern angekündigt. Das Projekt umfasst neue Perrons, verbesserte Zugänge und eine nachhaltige Energieversorgung.",
    image: "N/A",
    type: "News",
    originalContent: "<h1>SBB startet Modernisierung des Bahnhofs Luzern</h1><p>Die Schweizerischen Bundesbahnen haben heute den Startschuss für die umfassende Modernisierung des Bahnhofs Luzern gegeben. Das Projekt mit einem geschätzten Investitionsvolumen von über 500 Millionen Franken sieht die Erneuerung der Perronanlagen, die Verbesserung der Personenströme sowie den Einbau moderner Energieversorgungssysteme vor.</p><p>Die Bauarbeiten werden in mehreren Phasen durchgeführt, um den laufenden Betrieb so wenig wie möglich zu beeinträchtigen. Die erste Phase konzentriert sich auf den Gleisbau und die Erneuerung der Fahrleitungen.</p>",
    generatedContent: "<h1>Bahnhof Luzern wird modernisiert</h1><p>Die SBB investiert über 500 Millionen Franken in die umfassende Modernisierung des Bahnhofs Luzern. Das Grossprojekt umfasst neue Perrons, optimierte Personenströme und nachhaltige Energiesysteme.</p><p>Die Bauarbeiten starten in mehreren Phasen, wobei zunächst der Gleisbau und die Fahrleitungserneuerung im Fokus stehen. Der laufende Bahnbetrieb soll dabei möglichst wenig beeinträchtigt werden.</p>",
    metadata: {},
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-01-10")
  },
  {
    baseUrl: "https://bahnblogstelle.com",
    url: "https://bahnblogstelle.com/2026/01/neue-stadler-flirt-fuer-sob",
    title: "Neue Stadler FLIRT für die SOB bestellt",
    dateText: "15.01.2026",
    date: new Date("2026-01-15"),
    teaser: "SOB bestellt neue Triebzüge bei Stadler Rail.",
    generatedTeaser: "Die Südostbahn (SOB) hat bei Stadler Rail in Bussnang eine neue Serie von FLIRT-Triebzügen bestellt. Die Fahrzeuge sollen ab 2028 auf der Linie Voralpen-Express eingesetzt werden.",
    image: "N/A",
    type: "News",
    originalContent: "<h1>Neue Stadler FLIRT für die SOB bestellt</h1><p>Die Südostbahn (SOB) hat einen Vertrag mit Stadler Rail für die Lieferung neuer FLIRT-Triebzüge unterzeichnet. Die modernen Fahrzeuge werden auf dem Voralpen-Express zwischen St. Gallen und Luzern verkehren.</p>",
    generatedContent: "<h1>SOB bestellt neue FLIRT-Züge</h1><p>Die Südostbahn erweitert ihre Flotte mit neuen Stadler FLIRT-Triebzügen. Die Bestellung umfasst mehrere Einheiten, die ab 2028 den Voralpen-Express bedienen sollen.</p>",
    metadata: {},
    createdAt: new Date("2026-01-15"),
    updatedAt: new Date("2026-01-15")
  },
  {
    baseUrl: "https://www.baublatt.ch",
    url: "https://www.baublatt.ch/verkehrsinfrastruktur/neue-gleisanlagen-zuerich",
    title: "Neue Gleisanlagen für den Raum Zürich",
    dateText: "20.01.2026",
    date: new Date("2026-01-20"),
    teaser: "Erweiterung der Schieneninfrastruktur im Grossraum Zürich.",
    generatedTeaser: "Im Zuge der wachsenden Mobilitätsnachfrage investiert die Schweiz in den Ausbau der Gleisanlagen rund um Zürich. Der Gleisbau umfasst neue Weichenanlagen und moderne Fahrleitungssysteme.",
    image: "N/A",
    type: "News",
    originalContent: "<h1>Neue Gleisanlagen für den Raum Zürich</h1><p>Der Bund und die SBB planen umfangreiche Erweiterungen der Schieneninfrastruktur im Grossraum Zürich. Das Projekt sieht neue Weichenanlagen, zusätzliche Gleise und die Modernisierung der Fahrleitungen vor.</p><p>Die Arbeiten werden teilweise auch Kabeltiefbau und Projektleitung durch spezialisierte Unternehmen erfordern – genau die Kompetenzen, die IRISO Bau AG als Rail-Services-Anbieter bietet.</p>",
    generatedContent: "<h1>Ausbau der Gleisinfrastruktur in Zürich</h1><p>Die Schweiz investiert in neue Gleisanlagen im Grossraum Zürich. Der Ausbau umfasst Weichenanlagen, zusätzliche Gleise und modernisierte Fahrleitungen, um dem wachsenden Verkehrsaufkommen gerecht zu werden.</p>",
    metadata: {},
    createdAt: new Date("2026-01-20"),
    updatedAt: new Date("2026-01-20")
  },
  {
    baseUrl: "https://direkt.sob.ch",
    url: "https://direkt.sob.ch/archiv/fahrleitungserweiterung-2026",
    title: "SOB investiert in Fahrleitungserneuerung",
    dateText: "25.01.2026",
    date: new Date("2026-01-25"),
    teaser: "Südostbahn erneuert Fahrleitungen auf Streckenabschnitt Rapperswil–Pfäffikon.",
    generatedTeaser: "Die SOB hat Investitionen in die Erneuerung der Fahrleitungen auf dem Streckenabschnitt zwischen Rapperswil und Pfäffikon angekündigt. Die Arbeiten umfassen moderne Masten und verbesserte Isolatoren.",
    image: "N/A",
    type: "News",
    originalContent: "<h1>SOB investiert in Fahrleitungserneuerung</h1><p>Die Südostbahn erneuert die Fahrleitungen auf dem Streckenabschnitt Rapperswil–Pfäffikon. Die Modernisierung umfasst neue Masten, verbesserte Isolatoren und eine leistungsfähigere Stromversorgung.</p>",
    generatedContent: "<h1>Fahrleitungserneuerung bei der SOB</h1><p>Die Südostbahn investiert in die Modernisierung der Fahrleitungen zwischen Rapperswil und Pfäffikon. Neue Masten und Isolatoren sollen die Zuverlässigkeit der Stromversorgung erhöhen.</p>",
    metadata: {},
    createdAt: new Date("2026-01-25"),
    updatedAt: new Date("2026-01-25")
  },
  {
    baseUrl: "https://www.alstom.com",
    url: "https://www.alstom.com/press-releases/2026/01/alstom-schweiz-wartungsvertrag",
    title: "Alstom gewinnt Wartungsvertrag in der Schweiz",
    dateText: "28.01.2026",
    date: new Date("2026-01-28"),
    teaser: "Alstom übernimmt Wartung von Schienenfahrzeugen in der Zentralschweiz.",
    generatedTeaser: "Alstom hat einen mehrjährigen Wartungsvertrag für Schienenfahrzeuge in der Zentralschweiz unterzeichnet. Der Vertrag umfasst die Instandhaltung von rund 40 Fahrzeugen.",
    image: "N/A",
    type: "News",
    originalContent: "<h1>Alstom gewinnt Wartungsvertrag</h1><p>Der führende Schienenfahrzeughersteller Alstom hat einen neuen Wartungsvertrag in der Zentralschweiz abgeschlossen. Der Vertrag läuft über acht Jahre und umfasst die Instandhaltung von rund 40 Triebfahrzeugen.</p>",
    generatedContent: "<h1>Neuer Alstom-Wartungsvertrag</h1><p>Alstom sichert sich einen langfristigen Wartungsvertrag in der Zentralschweiz für rund 40 Schienenfahrzeuge. Der Vertrag hat eine Laufzeit von acht Jahren.</p>",
    metadata: {},
    createdAt: new Date("2026-01-28"),
    updatedAt: new Date("2026-01-28")
  },
  {
    baseUrl: "https://www.rhomberg-sersa.com",
    url: "https://www.rhomberg-sersa.com/news/gleisbau-innovation-2026",
    title: "Rhomberg Sersa präsentiert innovative Gleisbautechnik",
    dateText: "02.02.2026",
    date: new Date("2026-02-02"),
    teaser: "Neue Technologien im Gleisbau vorgestellt.",
    generatedTeaser: "Rhomberg Sersa hat auf einer Fachkonferenz neue Technologien für den maschinellen Gleisbau präsentiert. Die Innovationen versprechen schnellere und präzisere Gleiserneuerungen.",
    image: "N/A",
    type: "News",
    originalContent: "<h1>Innovative Gleisbautechnik von Rhomberg Sersa</h1><p>Auf der diesjährigen Fachkonferenz für Schieneninfrastruktur hat Rhomberg Sersa neue Technologien vorgestellt, die den maschinellen Gleisbau revolutionieren sollen. Durch den Einsatz von GPS-gestützten Messsystemen und automatisierten Stopfmaschinen können Gleiserneuerungen deutlich schneller und präziser durchgeführt werden.</p>",
    generatedContent: "<h1>Rhomberg Sersa innoviert im Gleisbau</h1><p>Rhomberg Sersa hat neue Technologien für den maschinellen Gleisbau vorgestellt. GPS-gestützte Messsysteme und automatisierte Stopfmaschinen ermöglichen schnellere und präzisere Arbeiten.</p>",
    metadata: {},
    createdAt: new Date("2026-02-02"),
    updatedAt: new Date("2026-02-02")
  },
  {
    baseUrl: "https://www.bls.ch",
    url: "https://www.bls.ch/de/unternehmen/medien/medienmitteilungen/kabeltiefbau-loetschberg",
    title: "BLS modernisiert Kabelinfrastruktur am Lötschberg",
    dateText: "05.02.2026",
    date: new Date("2026-02-05"),
    teaser: "Umfassende Erneuerung der Kabelanlagen am Lötschberg-Basistunnel.",
    generatedTeaser: "Die BLS investiert in die Erneuerung der Kabelinfrastruktur am Lötschberg-Basistunnel. Die Arbeiten umfassen Kabeltiefbau, neue Signalkabel und die Modernisierung der Kommunikationssysteme.",
    image: "N/A",
    type: "News",
    originalContent: "<h1>Kabelinfrastruktur am Lötschberg wird modernisiert</h1><p>Die BLS AG hat den Startschuss für die Erneuerung der Kabelinfrastruktur am Lötschberg-Basistunnel gegeben. Das Projekt umfasst Kabeltiefbauarbeiten, den Einzug neuer Signal- und Kommunikationskabel sowie die Modernisierung der Energieversorgung im Tunnel.</p>",
    generatedContent: "<h1>BLS erneuert Kabel am Lötschberg</h1><p>Die BLS modernisiert die Kabelinfrastruktur am Lötschberg-Basistunnel. Das Projekt umfasst Kabeltiefbau, neue Signalkabel und eine modernisierte Energieversorgung.</p>",
    metadata: {},
    createdAt: new Date("2026-02-05"),
    updatedAt: new Date("2026-02-05")
  },
  {
    baseUrl: "https://www.youtube.com/@SBBCFFFFSofficial/videos",
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    title: "Einblick in den Gleisbau: So werden Schienen verlegt",
    dateText: "2 months ago",
    date: new Date("2025-12-15"),
    teaser: "",
    generatedTeaser: "",
    image: "N/A",
    type: "Video",
    originalContent: "N/A",
    generatedContent: "<h1>Gleisbau hautnah</h1><p>Dieses Video zeigt den faszinierenden Prozess des Gleisbaus. Von der Vorbereitung des Untergrundes über das Verlegen der Schwellen bis hin zum präzisen Einbau der Schienen – jeder Handgriff muss sitzen.</p><p>Moderne Gleisbautechniken ermöglichen es, ganze Streckenabschnitte in wenigen Stunden zu erneuern.</p>",
    metadata: {
      duration: "12:34",
      views: "15.000 Aufrufe",
      uploadDate: "2 months ago",
      source: "SBB CFF FFS",
      icon: ""
    },
    createdAt: new Date("2025-12-15"),
    updatedAt: new Date("2025-12-15")
  },
  {
    baseUrl: "https://www.youtube.com/@RhsersaGroup/videos",
    url: "https://www.youtube.com/watch?v=abc123example",
    title: "Fahrleitungsbau: Sicherheit und Präzision auf der Schiene",
    dateText: "1 month ago",
    date: new Date("2026-01-12"),
    teaser: "",
    generatedTeaser: "",
    image: "N/A",
    type: "Video",
    originalContent: "N/A",
    generatedContent: "<h1>Fahrleitungsbau im Detail</h1><p>Der Fahrleitungsbau erfordert höchste Präzision und Sicherheitsbewusstsein. In diesem Video wird gezeigt, wie neue Fahrleitungen installiert und bestehende Systeme modernisiert werden.</p><p>Die Arbeiten erfolgen meist nachts, um den regulären Bahnbetrieb nicht zu stören.</p>",
    metadata: {
      duration: "8:45",
      views: "8.500 Aufrufe",
      uploadDate: "1 month ago",
      source: "Rhomberg Sersa Group",
      icon: ""
    },
    createdAt: new Date("2026-01-12"),
    updatedAt: new Date("2026-01-12")
  },
  {
    baseUrl: "https://www.linkedin.com/company/sob-suedostbahn",
    url: "(seed-001)-https://www.linkedin.com/company/sob-suedostbahn",
    title: "",
    dateText: "3j",
    date: new Date("2026-02-13"),
    teaser: "",
    generatedTeaser: "",
    image: "N/A",
    type: "LinkedIn",
    originalContent: "<p>Wir sind stolz auf unser Team! Unsere Gleisbau-Spezialistinnen und -Spezialisten haben dieses Wochenende bei herausfordernden Bedingungen eine Weichenerneuerung erfolgreich abgeschlossen. Danke für euren Einsatz! 💪🚂</p><p>hashtag#Gleisbau hashtag#SOB hashtag#Rail hashtag#Teamwork</p>",
    generatedContent: "",
    metadata: {
      icon: "",
      source: "SOB Südostbahn"
    },
    createdAt: new Date("2026-02-13"),
    updatedAt: new Date("2026-02-13")
  },
  {
    baseUrl: "https://www.linkedin.com/company/rhomberg-sersa-rail-group",
    url: "(seed-002)-https://www.linkedin.com/company/rhomberg-sersa-rail-group",
    title: "",
    dateText: "1sem.",
    date: new Date("2026-02-09"),
    teaser: "",
    generatedTeaser: "",
    image: "N/A",
    type: "LinkedIn",
    originalContent: "<p>Innovation im Gleisbau: Unser neues GPS-Tracking System für Schotterstopfungen ist jetzt im Einsatz. Effizienter, präziser und nachhaltiger als je zuvor.</p><p>hashtag#Innovation hashtag#Gleisbau hashtag#RhombergSersa hashtag#RailServices</p>",
    generatedContent: "",
    metadata: {
      icon: "",
      source: "Rhomberg Sersa Rail Group"
    },
    createdAt: new Date("2026-02-09"),
    updatedAt: new Date("2026-02-09")
  },
  {
    baseUrl: "https://www.sbbcargo.com",
    url: "https://www.sbbcargo.com/de/medien/news/2026-intermodal-express",
    title: "SBB Cargo lanciert neuen Intermodal-Express",
    dateText: "10.02.2026",
    date: new Date("2026-02-10"),
    teaser: "Neue Verbindung für den kombinierten Verkehr.",
    generatedTeaser: "SBB Cargo startet eine neue Intermodal-Express-Verbindung zwischen Basel und Chiasso. Der Dienst verkürzt die Transitzeit für Container um rund 20 Prozent.",
    image: "N/A",
    type: "News",
    originalContent: "<h1>SBB Cargo lanciert Intermodal-Express</h1><p>SBB Cargo hat eine neue Express-Verbindung für den kombinierten Verkehr zwischen Basel und Chiasso lanciert. Durch optimierte Trassenführung und kürzere Haltezeiten wird die Transitzeit für Container um rund 20 Prozent verkürzt.</p>",
    generatedContent: "<h1>Neuer Intermodal-Express von SBB Cargo</h1><p>SBB Cargo beschleunigt den Gütertransport mit einer neuen Express-Verbindung Basel–Chiasso. Container erreichen ihr Ziel 20 Prozent schneller als bisher.</p>",
    metadata: {},
    createdAt: new Date("2026-02-10"),
    updatedAt: new Date("2026-02-10")
  }
]);

print('✓ Seed data inserted: 12 sample rail articles (7 News, 2 Video, 2 LinkedIn, 1 Cargo News)');
