/* eslint-disable prettier/prettier */
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

export type ArticleDocument = Article & Document;

export enum ArticleType {
  Video = 'Video',
  News = 'News',
  LinkedIn = 'LinkedIn',
}

export interface Metadata {
  duration: string;
  views: string;
  uploadDate: string;
  source: string;
  icon: string;
}

@Schema({ timestamps: true })
export class Article {
  @Prop({ required: true })
  baseUrl: string;

  @Prop({ required: true, unique: true })
  url: string;

  @Prop({ required: false })
  title: string;

  @Prop({ required: false })
  imageTitleContext: string;

  @Prop({ required: false })
  dateText: string;

  @Prop({ required: false })
  date: Date;

  @Prop({ required: false })
  teaser: string;

  @Prop({ required: false })
  generatedTeaser: string;

  @Prop({ required: false })
  image: string;

  @Prop({ required: false })
  imageLocal: string;

  @Prop({ required: false })
  googleImage: string;

  @Prop({ type: String, enum: ArticleType, default: ArticleType.News })
  type: ArticleType;

  @Prop({ required: false })
  originalContent: string;

  @Prop({ required: false })
  generatedContent: string;

  @Prop({ type: Object, required: false })
  metadata?: Metadata;

  createdAt: Date; // Auto-generated by Mongoose
  updatedAt: Date; // Auto-generated by Mongoose
}

export const ArticleSchema = SchemaFactory.createForClass(Article);

// Full-text search index: weighted so title matches rank higher than content
ArticleSchema.index(
  {
    title: 'text',
    teaser: 'text',
    generatedTeaser: 'text',
    generatedContent: 'text',
    originalContent: 'text',
  },
  {
    weights: {
      title: 10,
      teaser: 5,
      generatedTeaser: 5,
      generatedContent: 2,
      originalContent: 1,
    },
    name: 'article_text_search',
  },
);
